SRCGrob <- function(
    tree = NULL,
    genes = NULL,
    filename = "SRC_tree.pdf",
    scale1 = 0.05443424,
    scale2 = 0.5 / 362,
    wid = 1.2,
    line.lwd = 3,
    length.from.node.edge = TRUE,
    seg1.col = "black",
    seg2.col = "green",
    add.polygons = TRUE,
    extra.len = 10,
    sig_shape = 3,
    sig_curve = 3,
    spread = 1,
    gene_line_dist = 0.1,
    colour.scheme = colours,
    gene.cex = 0.85,
    add.genes = FALSE,
    genes_on_nodes = FALSE,
    yaxis_position = "left",
    yaxis1.label = "SNVs",
    yaxis2.label = NULL,
    axis.label.cex = list(x = 1.55, y = 1.55),
    axis.cex = list(x = 1.45, y = 1.45),
    yaxis1.interval = NA,
    yaxis2.interval = NA,
    ylimit = NULL,
    xaxis.label = NULL,
    xaxis.space.left = 0,
    xaxis.space.right = 0,
    min.width = NULL,
    w.padding = NULL,
    nodes = "circle",
    rad = 0.1,
    label.nodes = TRUE,
    node.col = "grey29",
    labe.cex = NA,
    cluster.list = NULL,
    add.normal = FALSE,
    normal.cex = 1,
    title = NULL,
    title.cex = 1.7,
    title.y = NULL,
    title.y.units = "npc",
    ...
    ) {
    inputs <- prep.tree(
        tree,
        genes,
        add.polygons,
        yaxis_position,
        w.padding,
        colour.scheme
        );

    fixed_angle = pi / 6;

    clone.out <- make.clone.tree.grobs(
        ccf.df = inputs$in.tree.df,
        tree = inputs$tree,
        genes_df = inputs$genes.df,
        rad = rad,
        scale1 = scale1,
        scale2 = scale2,
        wid = wid,
        line.lwd = line.lwd,
        length.from.node.edge = length.from.node.edge,
        seg1.col = seg1.col,
        seg2.col = seg2.col,
        add.polygons = add.polygons,
        extra.len = extra.len,
        sig_shape = sig_shape,
        sig_curve = sig_curve,
        spread = spread,
        fixed_angle = fixed_angle,
        add.genes = add.genes,
        genes_on_nodes = genes_on_nodes,
        gene_line_dist = gene_line_dist,
        gene.cex = gene.cex,
        yaxis_position = yaxis_position,
        yaxis1.label = yaxis1.label,
        yaxis2.label = yaxis2.label,
        axis.label.cex = axis.label.cex,
        axis.cex = axis.cex,
        yaxis1.interval = yaxis1.interval,
        yaxis2.interval = yaxis2.interval,
        ylimit = ylimit,
        xaxis.label = xaxis.label,
        xaxis.space.left = xaxis.space.left,
        xaxis.space.right = xaxis.space.right,
        min.width = min.width,
        nodes = nodes,
        label.nodes = label.nodes,
        node.col = node.col,
        labe.cex = labe.cex,
        cluster.list = cluster.list,
        add.normal = add.normal,
        normal.cex = normal.cex,
        title = title,
        title.cex = title.cex,
        title.y = title.y,
        title.y.units = title.y.units,
        ...
        );			

    out_tree <- gTree(
        children = package_clone_grobs(clone.out),
        vp = clone.out$vp,
        cl = "SRCGrob"
        );
    
    return(list(out_tree, clone.out));
    }
